CREATE DATABASE BAN_HANG_CA_PHE_NHOM_4_K16;
USE BAN_HANG_CA_PHE_NHOM_4_K16;

CREATE TABLE CHUCVU (
    MA_CV CHAR(10) PRIMARY KEY,
    TEN_CV NVARCHAR(50) NOT NULL
);

CREATE TABLE NGUOIDUNG (
    MA_ND CHAR(10) PRIMARY KEY,
    MA_CV CHAR(10) NOT NULL,
    TEN_ND VARCHAR(255) NOT NULL,
    MK_ND VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    CONSTRAINT FK_MA_CV_IN_NGUOIDUNG FOREIGN KEY (MA_CV) REFERENCES CHUCVU(MA_CV)
);


CREATE TABLE DANHSACH_LOAISP (
    MA_LOAISP CHAR(10) PRIMARY KEY,
    TEN_LOAISP NVARCHAR(100) NOT NULL
);

CREATE TABLE DANHSACH_NHOMSP (
    MA_NHOMSP CHAR(10) PRIMARY KEY,
    TEN_NHOMSP NVARCHAR(100) NOT NULL
);

CREATE TABLE DANHSACH_SANPHAM (
    MA_SP CHAR(10) PRIMARY KEY,
    MA_LOAISP CHAR(10) NOT NULL,
    MA_NHOMSP CHAR(10) NOT NULL,
    TEN_SP NVARCHAR(100) NOT NULL,
    GIA_SP INT NOT NULL,
    XUATXU NVARCHAR(50) NOT NULL,
    GHICHU NVARCHAR(255),
    TEN_HINHSP VARCHAR(255),
    CONSTRAINT FK_MA_LOAISP_IN_DANHSACH_SANPHAM FOREIGN KEY (MA_LOAISP) REFERENCES DANHSACH_LOAISP(MA_LOAISP),
    CONSTRAINT FK_MA_NHOMSP_IN_DANHSACH_SANPHAM FOREIGN KEY (MA_NHOMSP) REFERENCES DANHSACH_NHOMSP(MA_NHOMSP)
);

CREATE TABLE DANHSACH_TONKHO (
    MA_SP CHAR(10) NOT NULL,
    SOLUONG INT NOT NULL,
    CONSTRAINT FK_MA_SP_IN_DANHSACH_TONKHO FOREIGN KEY (MA_SP) REFERENCES DANHSACH_SANPHAM(MA_SP)
);


CREATE TABLE DANHSACH_HINHSP (
    MA_HINHSP CHAR(10) PRIMARY KEY,
    MA_SP CHAR(10) NOT NULL,
    TEN_HINHSP VARCHAR(255) NOT NULL,
    CONSTRAINT FK_MA_SP_IN_DANHSACH_HINHSP FOREIGN KEY (MA_SP) REFERENCES DANHSACH_SANPHAM(MA_SP)
);

CREATE TABLE DANHSACH_PHANHOI (
    MA_PHANHOI CHAR(10) PRIMARY KEY,
    HOVATEN NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(255) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    NOIDUNG TEXT NOT NULL
);

CREATE TABLE DANHSACH_HOADON (
    MA_HD CHAR(10) PRIMARY KEY,
    MA_ND CHAR(10) NOT NULL,
    HO_NGUOIMUA NVARCHAR(10) NOT NULL,
    TEN_NGUOIMUA NVARCHAR(25) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    DIACHI_NGUOIMUA NVARCHAR(255) NOT NULL,
    NGAYLAP_HD DATETIME,
    TINHTRANG VARCHAR(20) NOT NULL,
    GHICHU NVARCHAR(255),
    CONSTRAINT FK_MA_ND_IN_DANHSACH_HOADON FOREIGN KEY (MA_ND) REFERENCES NGUOIDUNG(MA_ND)
);

CREATE TABLE CHITIET_HOADON (
    MA_CTHD CHAR(10) PRIMARY KEY,
    MA_HD CHAR(10) NOT NULL,
    MA_SP CHAR(10) NOT NULL,
    SOLUONG INT NOT NULL,
    GIA_SP INT NOT NULL,
    CONSTRAINT FK_MA_HD_IN_CHITIET_HOADON FOREIGN KEY (MA_HD) REFERENCES DANHSACH_HOADON(MA_HD),
    CONSTRAINT FK_MD_SP_IN_CHITIET_HOADON FOREIGN KEY (MA_SP) REFERENCES DANHSACH_SANPHAM(MA_SP)
);

